// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Location string `json:"location"`
}

type Job struct {
	ID       int      `json:"id"`
	JobTitle string   `json:"jobTitle"`
	Salary   string   `json:"salary"`
	Company  *Company `json:"company"`
}

type NewCompany struct {
	Name     string `json:"name"`
	Location string `json:"location"`
}

type NewJob struct {
	Cid      string `json:"cid"`
	JobTitle string `json:"jobTitle"`
	Salary   string `json:"salary"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
